dns:
  enable: true
  prefer-h3: true
  ipv6: false
  cache-algorithm: arc
  enhanced-mode: fake-ip
  use-hosts: true
  use-system-hosts: true
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - +.lan
    - +.local
    - +.m2m
    - +.bogon
    - +.localdomain
    - +.home.arpa
    - +.10.in-addr.arpa
    - +.254.169.in-addr.arpa
    - +.16.172.in-addr.arpa
    - +.17.172.in-addr.arpa
    - +.18.172.in-addr.arpa
    - +.19.172.in-addr.arpa
    - +.20.172.in-addr.arpa
    - +.21.172.in-addr.arpa
    - +.22.172.in-addr.arpa
    - +.23.172.in-addr.arpa
    - +.24.172.in-addr.arpa
    - +.25.172.in-addr.arpa
    - +.26.172.in-addr.arpa
    - +.27.172.in-addr.arpa
    - +.28.172.in-addr.arpa
    - +.29.172.in-addr.arpa
    - +.30.172.in-addr.arpa
    - +.31.172.in-addr.arpa
    - +.168.192.in-addr.arpa
    - +.msftconnecttest.com
    - +.msftncsi.com
    - local.adguard.org
    - injections.adguard.org
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.market.xiaomi.com
    - xbox.*.*.microsoft.com
    - +.xboxlive.com
    - +.ipv6.microsoft.com
    - +.turn.twilio.com
    - +.stun.twilio.com
    - stun.*.*
    - stun.*.*.*
    - time.windows.com
    - time.apple.com
    - time.asia.apple.com
    - time.ustc.edu.cn
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - localhost.work.weixin.qq.com
    - geosite:connectivity-check
    - geosite:private
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 223.5.5.5
  nameserver:
    - https://223.5.5.5/dns-query#skip-cert-verify=true
    - https://119.29.29.29/dns-query#skip-cert-verify=true
    # - https://8.8.8.8/dns-query#ecs=120.76.0.0/14&ecs-override=true
