proxy-groups-anchor:
  select: &select
    type: select
    include-all: true
    exclude_type: direct
  select-from: &select-from
    type: select
    proxies: [HK, TW, US, EU, SG, JP, KR, World, DIRECT]

proxy-groups:
  - name: HK
    <<: *select
    filter: é¦™æ¸¯|HK|HongKong|Hong Kong|ðŸ‡­ðŸ‡°
    icon: https://api.iconify.design/twemoji:flag-hong-kong-sar-china.svg
  - name: TW
    <<: *select
    filter: å°æ¹¾|TW|Taiwan|ðŸ‡¨ðŸ‡³|ðŸ‡¹ðŸ‡¼
    icon: https://api.iconify.design/twemoji:flag-china.svg
  - name: US
    <<: *select
    filter: ç¾Žå›½|US|United States|America|ðŸ‡ºðŸ‡¸
    icon: https://api.iconify.design/twemoji:flag-united-states.svg
  - name: EU
    <<: *select
    filter: æ¬§|EU|ðŸ‡ªðŸ‡º|è‹±|UK|GB|United Kingdom|Britain|England|ðŸ‡¬ðŸ‡§|æ³•|FR|France|ðŸ‡«ðŸ‡·|å¾·|DE|Germany|Deutschland|ðŸ‡©ðŸ‡ª
    icon: https://api.iconify.design/twemoji:flag-european-union.svg
  - name: SG
    <<: *select
    filter: æ–°åŠ å¡|ç‹®åŸŽ|SG|Singapore|ðŸ‡¸ðŸ‡¬
    icon: https://api.iconify.design/twemoji:flag-singapore.svg
  - name: JP
    <<: *select
    filter: æ—¥æœ¬|JP|Japan|ðŸ‡¯ðŸ‡µ
    icon: https://api.iconify.design/twemoji:flag-japan.svg
  - name: KR
    <<: *select
    filter: éŸ©å›½|KR|Korea|ðŸ‡°ðŸ‡·
    icon: https://api.iconify.design/twemoji:flag-south-korea.svg
  - name: World
    <<: *select
    icon: https://api.iconify.design/fluent-emoji-flat:world-map.svg

  - name: CDN
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:rocket.svg
  - name: AI
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:bookmark-tabs.svg
  - name: Telegram
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:ringed-planet.svg
  - name: Apple
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:red-apple.svg
  - name: Microsoft
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:window.svg
  - name: Download
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:card-file-box.svg

  - name: Default
    <<: *select-from
    icon: https://api.iconify.design/fluent-emoji-flat:bullseye.svg
