rule-providers-anchor:
  rules: &rules
    type: http
    behavior: classical
    format: text
    interval: 43200
  ip: &ip
    type: http
    behavior: ipcidr
    format: text
    interval: 43200
  domain: &domain
    type: http
    behavior: domain
    format: text
    interval: 43200

rule-providers:
  reject_non_ip_no_drop:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt
  reject_non_ip_drop:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt
  reject_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/reject.txt
  reject_domainset:
    <<: *domain
    url: https://ruleset.skk.moe/Clash/domainset/reject.txt
  # reject_extra_domainset:
  #   <<: *domain
  #   url: https://ruleset.skk.moe/Clash/domainset/reject_extra.txt
  reject_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/reject.txt
  speedtest:
    <<: *domain
    url: https://ruleset.skk.moe/Clash/domainset/speedtest.txt
  cdn_domainset:
    <<: *domain
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
  cdn_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
  stream_us_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/stream_us.txt
  stream_us_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/stream_us.txt
  stream_eu_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/stream_eu.txt
  stream_eu_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/stream_eu.txt
  stream_jp_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/stream_jp.txt
  stream_jp_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/stream_jp.txt
  stream_kr_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/stream_kr.txt
  stream_kr_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/stream_kr.txt
  stream_hk_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/stream_hk.txt
  stream_hk_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/stream_hk.txt
  stream_tw_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/stream_tw.txt
  stream_tw_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/stream_tw.txt
  ai_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
  telegram_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/telegram.txt
  telegram_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/telegram.txt
  apple_cdn:
    <<: *domain
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
  apple_services:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/apple_services.txt
  apple_cn_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt
  microsoft_cdn_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
  microsoft_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
  download_domainset:
    <<: *domain
    url: https://ruleset.skk.moe/Clash/domainset/download.txt
  download_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/download.txt
  lan_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
  lan_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
  domestic_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
  domestic_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
  direct_non_ip:
    <<: *rules
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
  china_ip:
    <<: *ip
    url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
