rules:
  # custom
  - RULE-SET,custom_direct,DIRECT
  # ruleset
  - RULE-SET,reject_domainset,REJECT
  - RULE-SET,speedtest,DIRECT
  - RULE-SET,cdn_domainset,CDN
  - RULE-SET,apple_cdn,DIRECT
  - RULE-SET,download_domainset,Download
  # no optimization
  - RULE-SET,reject_non_ip,REJECT
  - RULE-SET,reject_non_ip_drop,REJECT-DROP
  - RULE-SET,reject_non_ip_no_drop,REJECT
  - RULE-SET,reject_ip,REJECT
  - RULE-SET,lan_non_ip,DIRECT
  - RULE-SET,cdn_non_ip,CDN
  - RULE-SET,stream_us_non_ip,US
  - RULE-SET,stream_eu_non_ip,EU
  - RULE-SET,stream_jp_non_ip,JP
  - RULE-SET,stream_kr_non_ip,KR
  - RULE-SET,stream_hk_non_ip,HK
  - RULE-SET,stream_tw_non_ip,TW
  - RULE-SET,ai_non_ip,AI
  - RULE-SET,telegram_non_ip,Telegram
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,apple_services,Apple
  - RULE-SET,apple_cn_non_ip,DIRECT
  - RULE-SET,microsoft_cdn_non_ip,DIRECT
  - RULE-SET,microsoft_non_ip,Microsoft
  - RULE-SET,download_non_ip,Download
  - GEOSITE,geolocation-!cn@cn,DIRECT
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  # default
  - MATCH,Default
